---
apiVersion: v1
kind: Namespace
metadata:
  name: userapi

---
apiVersion: v1
kind: Secret
metadata:
  name: dockerregistrykey
  namespace: userapi
data:
  .dockerconfigjson: <REPLACE_ME>
type: kubernetes.io/dockerconfigjson